name: camsa_login
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  flutter_rating: ^0.0.2
  carousel_slider: ^1.3.0
  responsive_container: ^0.0.1
  flutter_datetime_picker: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/tec.png
    - assets/cafe.jpg
    - assets/Logoof.png
    - assets/volante_e-02.png
    - assets/icono1.jpg
    - assets/contra.png
    - assets/cuenta.png
    - assets/faqs.png
    - assets/mi_exp.png

  fonts:
    - family: whats
      fonts:
        - asset: assets/fonts/whats.ttf
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: Doritos
      fonts:
        - asset: assets/fonts/Pier_Sans/PierSans-Light.otf

    - family: Sabritas
      fonts:
        - asset: assets/fonts/Pier_Sans/PierSans-Medium.otf



